# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X99ZXxbqKExsXINCL8NgNknH0YTNNIYM
"""

class Student:
  def __init__(self,name,marks,age):
    self.name=name
    self.marks=marks
    self.age=age


s1=Student("shifa",77,23)
print("name is:",s1.name)
print("marks is:",s1.marks)
print("age is:",s1.age)

class Student:
    def __init__(self, name, m1, m2, m3):
        self.name = name
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3

    def avg(self):
        total = self.m1 + self.m2 + self.m3
        average = total / 3
        return average


s1 = Student("Shifa", 88, 80, 90)
print("Name is:",s1.name)
print("Marks is:",s1.m1)
print("Marks is:",s1.m2)
print("Marks is:",s1.m3)
print("average is:",s1.avg())

class Account:
  def __init__(self,balance,account_no):
    self.balance=balance
    self.account_number=account_no

a1=Account(10000,4357895)
print(a1.balance)
print(a1.account_number)

